README.md
Updated README to follow correct [README Template](https://gist.github.com/tylambe/7a4e4ddc76267d9ff2d5c226924e6e11l). Updated project title and description, as well as team roles and project usage. Still need to update:
> Installing Dependencies 
> Roadmap 
> Contributing 
> Style Guide
=> updated README to follow correct template

package-lock.json, package.json, src/api/index.js, src/api/models/Users.js, src/api/package-lock.json, src/api/package.json
Refactored old code to create users model. Moving on to admins, then Posts soon.
=> Users model

src/components/HomePage/Banner.js, src/components/HomePage/HomePage.js, src/components/Navigation/Navigation.jsx
Banner component added to the Homepage folder with header and button according to the wire frame. Added class names to elements react app renders properly.
=> created banner component with header and forum button

src/api/controllers/auth.js, src/api/package.json
-added controller folder to store controller methods
-added method for user creation
-added method for user verification
-added method for user authentication
=> added methods for user creation, authentication and verification.

package.json, src/App.js, src/components/HomePage/Banner.js, src/components/HomePage/HomePage.css, src/components/HomePage/HomePage.js, src/components/HomePage/Tag.js, src/components/Navigation/Navigation.jsx
- installed react-bootstrap for the navbar
- imported styling for bootstrap in App.js
- changed Navigation component to use navbar from react-bootstrap
- imported react navbar from react-bootstrap for the homepage
- added button types to buttons in components suggested by linter
=> React navbar

package.json, src/App.js
- installed react-router-dom for App.js
- added Router from react-router-dom to create routes where different pages will render
=> React router

src/App.js, src/components/Forum/Forum.css, src/components/Forum/Forum.js, src/components/Forum/ForumHeader.js, src/components/Forum/ForumPosts.js, src/components/Forum/Post.js, src/components/Forum/SearchTags.js, src/components/Navigation/Navigation.jsx
- added route to posts for forum
- created Forum component folder that has main components according to wireframe
- in the forum component:
- header component
- main forum posts component
- search post
-  post component
=> Forum component

src/App.js, src/components/authentication/Login/Login.js, src/components/authentication/Login/LoginForm.js, src/components/authentication/Register/Register.js, src/components/authentication/Register/RegisterForm.js, src/components/authentication/authentication.css
- created react route in for login and register
- created Login component with Login form 
- Register component with Register form 
- added CSS file for authentication
=> Login and Register forms

src/api/controllers/posts.js, src/api/controllers/users.js, src/api/db.js, src/api/routes/router.js, src/components/Forum/PostForm.js, src/components/Register/RegisterForm.js
-api routes nearly done, not clean but in.
=> near finalization of api routes.

package.json, src/api/controllers/posts.js, src/api/models/Posts.js, src/components/Forum/ForumPosts.js, src/components/Login/Login.js, src/components/Login/LoginForm.js, src/components/Navigation/Navigation.jsx
Reverts MCP-Foundation/Small-Stories#67
=> Revert "Api"

Client/package-lock.json, Client/src/components/Profile/UserPost.js, Server/controllers/posts.js, Server/models/Posts.js, Server/routes/router.js
-account page now shows a users posts as apposed to all posts,
=> working model from the morning.

Client/src/components/Forum/Forum.js, Client/src/components/Forum/ForumHeader.js
added form modal using react bootstrap for submit the form to create a post added model show and close states to forum
- linted both files 
- form submits and creates post!
=> Add modal to forum

Client/package.json, Client/src/components/Forum/Forum.css, Client/src/components/Forum/ForumHeader.js, Client/src/components/Forum/Post.js
- added more tag and category options, added grommet button to modal
- removed ant design components in Post, designed posts to look like the wire frame
- added styling to Forum.css
- added grommet icons as a dependency 
- linted, posts, and post form modal submit!
=> Post Component update

Client/src/components/Register/AvatarForm.js, Client/src/components/Register/Register.js, Client/src/components/Register/RegisterForm.js
- created avatar modal for user avatar customization
- added avatar modal to sign up form and changed sign up submit button to grommet component
- linted,  form does not submit yet
=> Created avatar form in sign up

Client/src/components/Forum/ForumPosts.js, Client/src/components/Forum/Post.js, Client/src/components/Forum/PostView.js, Server/controllers/users.js
- added use effect to fetch user data in post, post displays user's name and username on forum posts
- added avatar to user controllers for POST route to register a user
-linted forms work and posts render correctly!
=> Forum post

Client/src/components/Register/AvatarForm.js, Client/src/tables.sql, Server/controllers/likes.js, Server/controllers/users.js, Server/routes/router.js
- removed grommet from register form
- added like and unlike posts to controllers, created a route to post to likes but there is a bug
- added likes table for db
=> Liking posts

Client/src/components/Forum/Forum.css, Client/src/components/Forum/Post.js
- added like and unlike posts to controllers, created route to post to likes but there is a bug
=> Liking posts in Forum 

Client/src/components/Forum/Post.js, Client/src/contexts/profileContext.js, Server/controllers/users.js, Server/models/Users.js, Server/routes/router.js
changed the like components to use the persons like over just a random person.
=> likes are now from the current logged in user rather than a random user.

Server/routes/postRouter.js
re-added route that was shifted in routes migration.
=> re-added create a comment/create a post using new routes.

Client/src/components/Footer/Footer.css, Client/src/components/Footer/Footer.js, Client/src/components/Forum/Forum.css, Client/src/components/Forum/Forum.js, Client/src/components/Forum/ForumHeader.js, Client/src/components/Forum/ForumPosts.js, Client/src/components/HomePage/Tag.js, Client/src/components/Login/Login.css, Client/src/components/Login/LoginForm.js, Client/src/components/Register/Register.css, Client/src/components/Register/Register.js, Client/src/components/Register/RegisterForm.js, Client/src/contexts/tagContext.js
bug in forum posts, all posts not rendering
=> fixed bug in Forum for rendering all posts
